name: Test action
on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  hello_world_test_job:
    runs-on: ubuntu-latest
    name: A test job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: build # Checkout 'build' branch

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
        env:
          MY_VAR: "My test env variable"

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"